### ISSUE TITLE
Bintray Sunset

### ISSUE THREAD

**Issue by j-mew-s** [anti-social/prometheus-kt#7]
Will you be distributing this project via a service other than bintray when it becomes unavailable on 1st May? https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Thank you for your work!

**Comment by mcmarkj** [comment]
Hey @anti-social - any thoughts on this? 😄

**Comment by ethanmdavidson** [comment]
I haven't tried it with this project specifically, but I've had good success with [jitpack](https://jitpack.io) in the past. Try following the instructions here: https://jitpack.io/#anti-social/prometheus-kt

**Comment by anti-social** [comment]
Yeah, think to migrate to jitpack soon.

**Comment by anti-social** [comment]
Finally decided to upload artifacts to maven central. Try to use instructions from the readme. If have some troubles let me know.

https://search.maven.org/artifact/dev.evo.prometheus/prometheus-kt/0.1.1/jar
