### ISSUE TITLE
Issue with v0.1.1 release?

### ISSUE THREAD

**Issue by mattrussell-sonocent** [anti-social/prometheus-kt#9]
Did the v0.1.1 version publish correctly? Hitting https://jitpack.io/com/github/anti-social/prometheus-kt/v0.1.1/prometheus-kt-v0.1.1.pom comes back with:

```
Build failed. See the log at jitpack.io
```

**Comment by anti-social** [comment]
Version 0.1.1 was published on maven central: https://search.maven.org/search?q=g:dev.evo.prometheus

All you should have is `mavenCentral()` in your repositories configuration.

Basically I could fix building on Jitpack. Let me know if you really need it.

What's going wrong on Jitpack:
```
* What went wrong:
Execution failed for task ':signJsPublication'.
> Cannot perform signing task ':signJsPublication' because it has no configured signatory
```
We need to turn off package signing.
